AGAT_COLS = ["Gene_Models (N)",
        "Transcript_Models (N)",
        "CDS_Models (N)",
        "Exons (N)",
        "UTR5' (N)",
        "UTR3' (N)",
        "Overlapping_Gene_Models (N)",
        "Single Exon Gene Models (N)",
        "Single Exon Transcripts (N)",
        "Total Gene Space (Mb)",
        "Mean Gene Model Length (bp)",
        "Mean CDS Model Length (bp)",
        "Mean Exon Length (bp)",
        "Mean Intron Length (bp)",
        "Longest Gene Model Length (bp)",
        "Longest CDS Model Length (bp)",
        "Longest Intron Length (bp)",
        "Shortest Gene Model Length (bp)",
        "Shortest CDS Model Length (bp)",
        "Shortest Intron Length (bp)"]

RNASEQ_COLS = ["Transcript level_f1", 
            "Locus level_f1",
            "Matching transcripts:",
            "Matching loci:"]
